### ISSUE TITLE
Clarify documentation for config/platform inputs

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vs-intellicode#7]
Currently, [it appears](https://github.com/microsoft/vs-intellicode/blob/master/src/main.ts#L53) like both the `config` and `platform` inputs must be set, in order to customize either of them. Is that actually necessary? (e.g. would it make sense to just override the config or platform, but not both?). If so, it might be helpful to update the readme to call out this dependency.

Additionally, both inputs are called out as optional, but we don't specify what the default value is. If someone is building a C++ project, is the config/platform inferred from the project/build configuration in the codebase itself? If so, it might be helpful to call that out.

**Comment by catycaldwell** [comment]
Thanks @lostintangent for reviewing this. I'll get our README updated.

**Comment by DavidObando** [comment]
The current template inline documentation is still missing information on what the default values are.

```
- name: IntelliCode Team Completions
  uses: microsoft/vs-intellicode@v1.0
  with:
    # Only for C++ extractions. Sets the platform for the C++ build (ARM, Any CPU, etc).
    platform: # optional
    # Only for C++ extractions. Sets the configuration for the C++ build (Debug, Release).
    config: # optional
    # Use if you wish to override the directory where the repo to be trained is located at.
    directory: # optional
    # Use debug to override logs and display diagnostics verbosity
    logs: # optional
```

@catycaldwell this may be something we want to address soon. Any input?
